<a href="https://colab.research.google.com/github/isj0/Deep-Learning-with-PyTorch/blob/main/Deep_Learning_with_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [3]:
# basic list

my_list = [[1, 2, 3, 4, 5],
           [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

In [4]:
# numpy arrays

np1 = np.random.rand(3, 4)
np1

array([[0.9261691 , 0.77050519, 0.88691613, 0.66839928],
       [0.73553282, 0.03389235, 0.20650084, 0.68295211],
       [0.26579032, 0.77642547, 0.70988083, 0.47908512]])

In [5]:
np1.dtype

dtype('float64')

In [6]:
# Tensors

tensor_2d = torch.randn(3, 4)
tensor_2d

tensor([[ 1.4545, -0.4983,  1.2347, -0.4527],
        [-0.4220,  0.6006, -1.1456,  0.5998],
        [-0.7752, -0.2394,  0.0231, -1.2591]])

In [7]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.9262, 0.7705, 0.8869, 0.6684],
        [0.7355, 0.0339, 0.2065, 0.6830],
        [0.2658, 0.7764, 0.7099, 0.4791]], dtype=torch.float64)

In [9]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
my_torch = my_torch.reshape(2, 5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
my_torch2 = torch.arange(15)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [18]:
my_torch2 = my_torch2.reshape(5, -1)
my_torch2

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

In [19]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
my_torch4 = my_torch3.view(2, 5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
my_torch6 = my_torch5.reshape(2, 5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [23]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [24]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [25]:
# Slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
my_torch7[7:]

tensor([7, 8, 9])

In [27]:
my_torch8 = my_torch7.reshape(5, 2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [28]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [29]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [30]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [31]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [32]:
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [33]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [34]:
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [36]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [37]:
tensor_a % tensor_b

tensor([1, 2, 3, 4])

In [38]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [39]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [40]:
tensor_a = tensor_a + tensor_b
tensor_a

tensor([ 6,  8, 10, 12])

In [41]:
tensor_a.add_(tensor_b)
tensor_a

tensor([11, 14, 17, 20])